### PR TITLE
Input arg

### PR DESCRIPTION
**Pull request by maboiteaspam**
In fact, i was also needing the input argument.

### CODE REVIEW

**Comment by thlorenz** [comment]
Will look at this when output arg PR is done and merged.
But same goes here, please add a test.

**Comment by maboiteaspam** [comment]
Hi,

take a look at that one, there is all commits inside.
When you are fine, i ll squash this.

**Comment by abritinthebay** [comment]
This would be really nice to have right now :(

**Comment by thlorenz** [comment]
Understood @abritinthebay .. just a question of my time .. need some help here so made you collaborator.

Please review and help squashing the commits .. to me on quick look it appears good. Once reviewed and squashed please merge to master following [this guide](https://gist.github.com/thlorenz/f7df0daf13c6f6c1fa84).
I will then version and publish to npm.

Thanks.

**Comment by abritinthebay** [comment]
Totally understand (have the same problem myself with some OSS I maintain). I'll take a look at the guide  and try to get this merged asap.

**Comment by abritinthebay** [comment]
@maboiteaspam - can you squash on your end? (will be much much easier).

**Comment by bendrucker** [comment]
I'm going to go ahead and close this and #24. To me this is considerably less valuable/justified than #26 which adds lower level functionality. Here it seems like we're just adding a bunch of JS code instead of just doing `cat app.js | exorcist...` and `exorcist... > out.js`.

**Comment by jasonkarns** [comment]
@bendrucker have you seen any of the comments on #22 ?
https://github.com/thlorenz/exorcist/issues/22#issuecomment-145913672
https://github.com/thlorenz/exorcist/issues/22#issuecomment-145916640

Without an output argument, exorcist isn't flexible enough to be used via npm-scripts (you can't pass extra options to npm-scripts that are redirecting output) nor can you write the output to the same file as input.

**Comment by jasonkarns** [comment]
This needs reopened. Without an input argument, it's impossible to write the output to same input file.

```
cat bundle.js | exorcist bundle.js.map > bundle.js
```

Because the shell truncates `bundle.js` prior to `cat` running in preparation for writing. This is a huge limitation for efficient use of exorcist in npm-scripts.

**Comment by bendrucker** [comment]
No thanks. Why should exorcist support overriding the same file when this problem occurs with virtually all Unix tools? Overwriting a file in a shell statement is unsafe.

**Comment by jasonkarns** [comment]
This is why most other unix tools support specifying the outputfile name via an option!

**Pull request closed without merging**
