### PR TITLE
add output argument

### PR DESCRIPTION
**Pull request by maboiteaspam**
see 
https://github.com/thlorenz/exorcist/issues/22

### CODE REVIEW

**Comment by thlorenz** [comment]
LGTM is it possible to add a test for this?
Don't have to use `-o` but pass an `output` arg to ensure it'll write there instead to stdout.
Thanks.

**Comment by maboiteaspam** [comment]
I still need to check it, and update README file, this is not yet mergeable.

But let me know about the overall changes proposal please.

**Comment by maboiteaspam** [comment]
ok, that one pass the tests and is more complete.

**Comment by jasonkarns** [comment]
Can we bring back the flag arguments? (Though something besides -o/--output since that doesn't distinguish from the mapfile.) This way the commands are self-documenting and the args can be reordered.

**Comment by maboiteaspam** [comment]
I d be happy to do that, depending of @thlorenz comments.

This say i can only suggest to use the commit here
https://github.com/maboiteaspam/exorcist/commit/1902bf3cc725fee753a5942a1931325bb52c0d97

I don t really want to fork myself.

**Comment by maboiteaspam** [comment]
whatever happen to that pr, i m thinking to change it someday to better detect arguments vs stream via

`process.stdin.isTTY`

Would be way more suitable than

`output ? fs.createWriteStream(output) : process.stdout`

https://nodejs.org/api/process.html#process_process_stdout

Otherwise i d happy to close it to release my log, thanks.

**Comment by abritinthebay** [comment]
Any movement with this?

**Comment by abritinthebay** [comment]
I think adding the flag back this could be easily merged in (and as a collaborator I'm happy to do it).

Once that is done (and tested) then... lets go! :)

**Comment by jasonkarns** [comment]
Need to resurrect this for the use-cases already noted on #22 

https://github.com/thlorenz/exorcist/issues/22#issuecomment-145913672
https://github.com/thlorenz/exorcist/issues/22#issuecomment-145916640

Without an output argument, exorcist isn't flexible enough to be used via npm-scripts (you can't pass extra options to npm-scripts that are redirecting output) nor can you write the output to the same file as input.

**Comment by benburrill** [comment]
I also think this should be reopened.  I want my npm script to output the file to a build directory that doesn't generally exist.  I can use mkdir to create it, and that's what I'm doing, but it's kinda annoying because exorcist DOES create the missing directory when outputting the map file, it just doesn't do so in time for the redirection to use it.  So with `-o`, my npm scripts would be cleaner.

**Pull request closed without merging**
